package net.iqaddons.mod.manager;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import lombok.extern.slf4j.Slf4j;
import net.fabricmc.loader.api.FabricLoader;
import net.iqaddons.mod.model.etherwarp.EtherwarpCategory;
import org.jetbrains.annotations.NotNull;

import java.io.Reader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Slf4j
public class EtherwarpCategoryToggleManager {

    private static final EtherwarpCategoryToggleManager INSTANCE = new EtherwarpCategoryToggleManager();

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private final Map<String, Boolean> toggles = new LinkedHashMap<>();

    private EtherwarpCategoryToggleManager() {
        load();
    }

    public static EtherwarpCategoryToggleManager get() {
        return INSTANCE;
    }

    public synchronized void syncWithCategories(@NotNull List<EtherwarpCategory> categories) {
        List<String> incoming = new ArrayList<>();
        for (EtherwarpCategory category : categories) {
            incoming.add(category.name());
            toggles.putIfAbsent(category.name(), category.enabled());
        }

        toggles.entrySet().removeIf(entry -> !incoming.contains(entry.getKey()));
        save();
    }

    public synchronized boolean isCategoryEnabled(@NotNull String categoryName) {
        return toggles.getOrDefault(categoryName, true);
    }

    public synchronized void setCategoryEnabled(@NotNull String categoryName, boolean enabled) {
        toggles.put(categoryName, enabled);
        save();
    }

    public synchronized @NotNull Map<String, Boolean> getAll() {
        return Collections.unmodifiableMap(new LinkedHashMap<>(toggles));
    }

    private @NotNull Path getConfigDir() {
        Path fabricConfigDir = FabricLoader.getInstance().getConfigDir();
        if (fabricConfigDir != null) {
            return fabricConfigDir.resolve("iq");
        }

        // Fallback defensivo para ambientes onde configDir ainda nao foi inicializado.
        Path userDir = Paths.get(System.getProperty("user.dir", "."));
        return userDir.resolve("config").resolve("iq");
    }

    private @NotNull Path getTogglesFile() {
        return getConfigDir().resolve("etherwarp_category_toggles.json");
    }

    private synchronized void load() {
        toggles.clear();

        Path togglesFile = getTogglesFile();

        if (!Files.exists(togglesFile)) {
            return;
        }

        try (Reader reader = Files.newBufferedReader(togglesFile, StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            JsonObject categories = root.getAsJsonObject("categories");
            if (categories == null) return;

            for (Map.Entry<String, JsonElement> entry : categories.entrySet()) {
                if (!entry.getValue().isJsonPrimitive()) continue;
                toggles.put(entry.getKey(), entry.getValue().getAsBoolean());
            }
        } catch (Exception e) {
            log.warn("Failed to load Etherwarp category toggles", e);
        }
    }

    private synchronized void save() {
        try {
            Path configDir = getConfigDir();
            Path togglesFile = getTogglesFile();

            Files.createDirectories(configDir);

            JsonObject root = new JsonObject();
            JsonObject categories = new JsonObject();
            for (Map.Entry<String, Boolean> entry : toggles.entrySet()) {
                categories.addProperty(entry.getKey(), entry.getValue());
            }

            root.addProperty("_comment", "Auto-generated by IQ. Toggle Etherwarp categories here or using the selector screen.");
            root.add("categories", categories);

            try (Writer writer = Files.newBufferedWriter(togglesFile, StandardCharsets.UTF_8)) {
                GSON.toJson(root, writer);
            }
        } catch (Exception e) {
            log.warn("Failed to save Etherwarp category toggles", e);
        }
    }
}


