# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
kotlin.jvm.target.validation.mode=warning

# Loader Properties
minecraft_version=26.2
loader_version=0.19.5
fabric_version=0.160.0+26.2

# Mod Properties
mod_version=1.0.4
maven_group=net.iqaddons.mod
archives_base_name=iq

# Dependencies
resourcefulconfig_version=5.0.0
modmenu_version=20.0.2
discord_rpc_version=1.0.3
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20
